# Generated by Django 3.2.19 on 2023-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
