# Generated by Django 3.2.19 on 2023-05-08 16:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.article_image_file_path),
        ),
    ]
