# Generated by Django 3.2.19 on 2023-05-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=32)),
                ('name', models.CharField(default=None, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
        ),
    ]
