# Generated by Django 3.2.19 on 2023-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attributevariants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevariants',
            old_name='article',
            new_name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='attributes',
            field=models.ManyToManyField(to='core.AttributeVariants'),
        ),
    ]
