# Generated by Django 3.2.19 on 2023-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230509_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevariants',
            old_name='articles',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='attributes',
            field=models.ManyToManyField(related_name='_core_article_attributes_+', to='core.AttributeVariants'),
        ),
    ]
