# Generated by Django 3.2.19 on 2023-05-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230509_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevariants',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='attributes',
            field=models.ManyToManyField(to='core.AttributeVariants'),
        ),
    ]
