# Generated by Django 3.2.19 on 2023-05-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230510_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '5. Article'},
        ),
        migrations.AlterModelOptions(
            name='attributevariants',
            options={'verbose_name_plural': '5. Article Attributes'},
        ),
    ]
