# Generated by Django 3.2.19 on 2023-05-10 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230510_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '1. Article'},
        ),
        migrations.AlterModelOptions(
            name='attributevariants',
            options={'verbose_name_plural': '2. Article Attributes'},
        ),
        migrations.AddField(
            model_name='attributevariants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
