# Generated by Django 3.2.19 on 2023-05-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230511_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name_plural': '3. Article Image'},
        ),
    ]
