# Generated by Django 3.2.19 on 2023-05-11 00:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_articleimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=core.models.article_image_file_path),
        ),
    ]
