# Generated by Django 3.2.19 on 2023-05-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230511_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uploaded_images',
        ),
    ]
