# Generated by Django 3.2.19 on 2023-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_article_uploaded_images'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='core_articl_title_2488db_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['short_description'], name='core_articl_short_d_deb6de_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevariants',
            index=models.Index(fields=['type'], name='core_attrib_type_d5f6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='core_catego_name_6ef604_idx'),
        ),
    ]
